spring:
  profiles:
    active: local #Local 개발 환경

# Local 환경
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql # 시작할 때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
server:
  port: 8787
